### ISSUE TITLE
Rassemblement de tutos

### ISSUE THREAD

**Issue by moddeur-ultime** [Les-Moddeurs-Francais/Documentation-Forge#199]
## Informations

**Autheur :** knightmar

## Description
faire une page sur la doc avec les principales chaîne yt, sites internet, docs etc pour trouver plus simplement des tutos de modding

**Comment by knightmar** [comment]
liste des chaînes :
https://youtube.com/c/ZomZD
https://youtube.com/c/Cy4sModding
https://youtube.com/c/TKaupenjoe
https://youtube.com/c/TechnoVisionTV
https://youtube.com/c/TurtyWurty

liste des sites :
https://forge-doc.lesmoddeursfrancais.com/
https://forge.gemwire.uk/wiki/Main_Page/1.16
